#!/usr/bin/env python3
"""Render docs/data-sources.md from registry/sources.yaml.

The registry is the single source of truth. This script exists so the documentation cannot
drift from it -- regenerate rather than hand-edit docs/data-sources.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]


def flow(v) -> str:
    if v is None:
        return ""
    if isinstance(v, (list, tuple)):
        return ", ".join(str(x) for x in v)
    return " ".join(str(v).split())


def main() -> None:
    spec = yaml.safe_load((ROOT / "registry" / "sources.yaml").read_text())
    out: list[str] = []
    w = out.append

    w("# Data Sources")
    w("")
    w("*Generated from [`registry/sources.yaml`](../registry/sources.yaml) by "
      "`scripts/render_source_matrix.py`. Do not edit this file directly.*")
    w("")
    w(f"Registry version {spec['registry_version']} · audited {spec['audited_on']} · "
      f"{len(spec['sources'])} sources ingested, {len(spec['deferred_sources'])} deferred.")
    w("")
    w("Every URL and HTTP status below was verified by live request on the audit date. A 403 "
      "against an ICPSR-hosted dataset means the CDN rejects browserless clients, not that "
      "the dataset is missing.")
    w("")
    w("## Matrix")
    w("")
    w("| Source | Publisher | Grain | Years | Access | Identifier | Status | HTTP |")
    w("|---|---|---|---|---|---|---|---|")
    for s in spec["sources"]:
        years = f"{s.get('coverage_start_year','')}–{s.get('coverage_end_year','')}"
        w(f"| `{s['source_id']}` | {flow(s.get('publisher'))} | "
          f"{flow(s.get('geographic_level'))} | {years} | {flow(s.get('access_method'))} | "
          f"`{flow(s.get('primary_identifier'))}` | {flow(s.get('ingestion_status'))} | "
          f"{s.get('verified_http_status','')} |")
    w("")

    w("## Detail")
    w("")
    for s in spec["sources"]:
        w(f"### `{s['source_id']}` — {flow(s.get('dataset_name'))}")
        w("")
        w(flow(s.get("dataset_description")))
        w("")
        w(f"- **Publisher** {flow(s.get('publisher'))}")
        w(f"- **URL** {s.get('source_url','')}")
        if s.get("documentation_url"):
            w(f"- **Documentation** {s['documentation_url']}")
        if s.get("api_endpoint"):
            w(f"- **Endpoint** `{s['api_endpoint']}`")
        w(f"- **Access** {flow(s.get('access_method'))} · "
          f"**verified HTTP** {s.get('verified_http_status','')}")
        w(f"- **Coverage** {s.get('coverage_start_year','')}–{s.get('coverage_end_year','')} · "
          f"**updated** {flow(s.get('update_frequency'))}"
          + (f" · **latest release** {flow(s.get('latest_release_date'))}"
             if s.get("latest_release_date") else ""))
        w(f"- **Licence** {flow(s.get('license'))}")
        w(f"- **Primary identifier** `{flow(s.get('primary_identifier'))}`")
        if s.get("ingestion_note"):
            w(f"- **Ingestion note** {flow(s['ingestion_note'])}")
        if s.get("fallback"):
            fb = s["fallback"]
            w(f"- **Fallback** `{fb.get('api_endpoint','')}` "
              f"(HTTP {fb.get('verified_http_status','')}) — {flow(fb.get('note'))}")
        if s.get("decision"):
            w(f"- **Decision** {flow(s['decision'])}")
        lim = s.get("known_limitations") or []
        if lim:
            w("")
            w("**Known limitations**")
            w("")
            for item in lim:
                w(f"- {flow(item)}")
        for key in ("headline_figures", "coverage_measured"):
            if s.get(key):
                w("")
                w(f"**{key.replace('_', ' ').title()}**")
                w("")
                for k, v in s[key].items():
                    w(f"- `{k}`: {v}")
        w("")

    w("## Evaluated and deliberately not ingested")
    w("")
    w("A dataset enters the production platform only when its source is defensible, its "
      "methodology is understood, its identifiers reconcile, and it adds analytical value "
      "the platform does not already have. These did not clear that bar for Phase 1.")
    w("")
    for d in spec["deferred_sources"]:
        w(f"### `{d['source_id']}`")
        w("")
        w(flow(d["reason"]))
        w("")

    (ROOT / "docs" / "data-sources.md").write_text("\n".join(out) + "\n")
    print(f"wrote docs/data-sources.md ({len(out)} lines)", file=sys.stderr)


if __name__ == "__main__":
    main()
